"use strict";
// Q#3 is store 10 numbers in differnt Variables
var num1 = 1;
var num2 = 2;
var num3 = 3;
var num4 = 4;
var num5 = 5;
var num6 = 6;
var num7 = 7;
var num8 = 8;
var num9 = 9;
var num10 = 10;
console.log("num1 =", num1);
console.log("num2 =", num2);
console.log("num3 =", num3);
console.log("num4 =", num4);
console.log("num5 =", num5);
console.log("num6 =", num6);
console.log("num7 =", num7);
console.log("num8 =", num8);
console.log("num9 =", num9);
console.log("num10 =", num10);
